### ISSUE TITLE
Uncaught TypeError: Cannot read property 'topleft' of undefined

### ISSUE THREAD

**Issue by undefinedzain** [Twista/leaflet-google-places-autocomplete#2]
i got this, i have a leaflet map with many datas,
basically i want to search my datas based on location i search with this plugin.
please the solution, thank you

**Comment by Twista** [comment]
Hey,

this library does not search in your data, it just provide possibility to search in places api (based on user input) and then have a callback.

can you send bit more of output (which line throws it) and best will be send not working example

also what version of leaflet do you use ? do you have google places API library included ?

**Comment by undefinedzain** [comment]
Hey,
i know it doesn't search my data,,,
just point the map to location i get from autocomplete right ?
but i have problem in adding that search engine box to my map,
in this map i want to know my datas that in that location i get.

**Comment by Twista** [comment]
Yep, its right. 

can you provide more info please ? as i mentioned in last comment ? version of leaflet with more details about the error 

thanks

**Comment by Twista** [comment]
just tried the plugin with both version of leaflet (1.0.1 and 0.7) and works

based on what you said, it seems you are not adding valid map object into `addTo` method

please use http://plnkr.co/ or https://jsfiddle.net/ to create some example which is failing, otherwise i cannot help you

**Comment by undefinedzain** [comment]
hello,
i have on https://jsfiddle.net/gcr6nq6s/

and i used it inside my map.js
it get error on
corner = map._controlCorners[pos];

**Comment by Twista** [comment]
It seems its just copy-paste of my code. there is not much to check tbh. Please improve the example

thanks

**Comment by JCCabreraMX** [comment]
I have the same issue. Did you solve it? How did  you solve so??

**Comment by Twista** [comment]
please provide example :)
