### ISSUE TITLE
Cannot read property 'lat' of null

### ISSUE THREAD

**Issue by mykolakozyr** [Twista/leaflet-google-places-autocomplete#3]
While using the custom options:
`            new L.Control.GPlaceAutocomplete({
                position: "topleft",
                callback: function(location){
                    map.panTo(location);
                }
                }).addTo(map);`
I got an error: 

> Uncaught TypeError: Cannot read property 'lat' of null

However, it works great with no custom options:
`new L.Control.GPlaceAutocomplete().addTo(map);`

I want to use custom options for `zoomTo(location)`, instead of `panTo(location)`

What could be the problem?
Thank you in advance

**Comment by khelal** [comment]
Here's how I fixed it on my local project:

`

    new L.Control.GPlaceAutocomplete({
    callback: function(location){
        map.panTo([
          location.geometry.location.lat(),
          location.geometry.location.lng()
          ]);
        map.fitBounds([
               [location.geometry.viewport.getSouthWest().lat(),
                location.geometry.viewport.getSouthWest().lng()],
               [location.geometry.viewport.getNorthEast().lat(),
                location.geometry.viewport.getNorthEast().lng()]
              ]);
    }}).addTo(map);
`

**Comment by mykolakozyr** [comment]
@khelal thanks a lot. It works great
