### ISSUE TITLE
Compact search icon

### ISSUE THREAD

**Issue by jekuno** [Twista/leaflet-google-places-autocomplete#4]
What do you think about tuning the search control to be more compact so that it unfolds on click - similar to what `leaflet-search` does (see http://labs.easyblog.it/maps/leaflet-search/examples/simple.html for example).

Maybe on could provide a `collapsed` flag to switch between compact and expanded appearance.

**Comment by Twista** [comment]
thanks for advice, will definitely take a look 

- will keep the issue open until i will come up with something :)

**Comment by Twista** [comment]
Hello again @jekuno !

sorry for long delay, but christmas + vacation. Anyway. Just pushed draft of collapsed mode. Its in current master, but not tagged yet. 

Do you mind to check if it looks/works as you want ? 

from my side it looks ok

**Comment by jekuno** [comment]
Thanks for working on it. If you pull in #6 I think we're ready to go.

**Comment by Twista** [comment]
thanks for the PR, will test it in hour or so. 

I was thinking also about some css-transition when showing the input. will take a look today too.

I plan to tag release till Sunday, if you are ok with

**Comment by jekuno** [comment]
All right. Sounds good. Happy coding!

**Comment by Twista** [comment]
Okay, done.

New version published https://github.com/Twista/leaflet-google-places-autocomplete/releases/tag/v0.0.6

did a small improvement in icon positioning and added some css transitions :)

closing issue, thanks for your input and help :)

**Comment by jekuno** [comment]
Nice. I noticed two minor issues:

- Issue 1: Search for anything. Then close the search input (by clicking outside of the search results box twice). Then open the search tool once more by clicking on the magnifier.
Observed: The search box still contains the previously entered text (which is good). But you also see a search result column with marker artifacts from the previous search result. You need to type anything into the search field to update/fix the marker list.
- Issue 2: The button now is 30x30 whereas all the other leaflet buttons are 26x26 by default. If you use the google places search in an bar with other buttons it doesn't look too nice.

**Comment by Twista** [comment]
I thought 30x30 is default, will adjust it in a sec

**Comment by Twista** [comment]
and to the issue 1 - you mean that marker is still present on the map ? 

the list is about gmaps autocomplete - hard to handle. but what about cleaning the input (and therefore suggestion list) when searchbox is hidden ?

**Comment by Twista** [comment]
@jekuno just checked leaflet examples and buttons are 30x30 (see http://leafletjs.com/examples/quick-start/)

**Comment by jekuno** [comment]
Issue 1: see the following screenshot (tested in Chrome):
![marker-artifacts](https://cloud.githubusercontent.com/assets/10961144/22154345/6fc2cd62-df2b-11e6-9479-84632861c9a8.jpg)
I can reproduce it as described above (do NOT select any of the search results but simply close the search input by clicking outside). I would prefer if the text which had been entered originally would stay in the input field so that you can simply select a different search result from the list if you picked the wrong one.

Issue 2: http://leafletjs.com/examples/quick-start/ doesn't work for me right now. However the sourcecode defines 26px as follows: https://github.com/Leaflet/Leaflet/blob/master/dist/leaflet.css#L269
Do we have additional 4px added anywhere?

**Comment by Twista** [comment]
ad 2: its interesting - see screen
![fullscreen_20_01_17_16_19](https://cloud.githubusercontent.com/assets/1297511/22154623/7f832ff2-df2c-11e6-97fe-4429855b6689.png)
+ any other control i have in another project has 30x30 too

atm is 30x30 default and you can change size by overriding css

ad 1: will take a look closer and try to come up with something :)

**Comment by jekuno** [comment]
1) all right
2) I see. The example page adds the `leaflet-touch` class which is (probably) primarily meant to be used on mobile devices (bigger buttons for better usability as defined here with 30px: https://github.com/Leaflet/Leaflet/blob/master/dist/leaflet.css#L302). So your search element should look good both with `leaflet-touch` (30px) and without `leaflet-touch` (26px).

**Comment by Twista** [comment]
2: good catch, will check more examples during the weekend and will try to re-use those to look good on both. thanks for investigation.
