### ISSUE TITLE
Disabling the "enter" key

### ISSUE THREAD

**Issue by khelal** [Twista/leaflet-google-places-autocomplete#5]
the plugin works well when choosing a location with a click. however, when there's only one answer, a normal UX would be to press ENTER to choose it. This break the app.

**Comment by Twista** [comment]
thanks for the issue, will take a look what i can do. Its more likely google-autocomplete stuff, not sure if will be able

**Comment by edprince** [comment]
Using the example page, I'm adding a callback function like so:

```js
new L.Control.GPlaceAutocomplete({
  callback: function(location) {
    map.panTo(location);
  }
}).addTo(map);
```
But getting an error: 

> caught TypeError: Cannot read property 'lat' of null

Any ideas?

**Comment by Twista** [comment]
Hey @edprince it seems they changes signature a bit, which is weird.

instead of location you are probably getting place object, to fix that try this
```
            new L.Control.GPlaceAutocomplete({
                callback: function(place){
                    var loc = place.geometry.location;
                    map.panTo([loc.lat(), loc.lng()]);
                }
            }).addTo(map);
```
