### ISSUE TITLE
Wrong location when using map.setView and map.setZoom

### ISSUE THREAD

**Issue by mwort** [Twista/leaflet-google-places-autocomplete#8]
Hi, neat little plugin. Just thought I'd correct your example in the README which uses ```map.setView and map.setZoom``` in succession. This leads to the wrong places being found as pointed out here:
https://github.com/Leaflet/Leaflet/issues/426

It's recommended to use:
```
map.setView( [lat, lon], zoomlevel);
```

Hope that makes sense.

**Comment by Twista** [comment]
thanks for clarification and link!

example usage is fixed now :)
