### ISSUE TITLE
tooltip button

### ISSUE THREAD

**Issue by astomas** [Twista/leaflet-google-places-autocomplete#9]
Hi, is there a way to add a tooltip title to the search button?

**Comment by Twista** [comment]
HI @astomas, afaik there is none at the moment.

**Comment by astomas** [comment]
Ok I've found a way:
"var buttonR =  L.DomUtil.get(objGooglePlace.icon);
		buttonR.title = "Search...";"
where objGooglePlace is a standard Google-Place object.

**Comment by Twista** [comment]
perfect, closing issue then :)
